### ISSUE TITLE
Could you publish codes soon?

### ISSUE THREAD

**Issue by wenchen4321** [dariofuoli/RLSP#1]
What a amazing work! I am very interested about the running time of this job. Could you publish the codes of RLSP? So I can test it on my computer. Thank you very much!

**Comment by lzqcode** [comment]
I am also very interested in this project. When can you publish the code?

**Comment by Shuyun-Wang** [comment]
I also witing for the code of this fabulous model,+1.

**Comment by dariofuoli** [comment]
I uploaded a simple evaluation script for the pre-trained RLSP-128 model. You can find it under "evaluate". The code is tested in tensorflow 1.14. Let me know if you have questions regarding the code. Sorry for the delay.

**Comment by GuideWsp** [comment]
> I uploaded a simple evaluation script for the pre-trained RLSP-128 model. You can find it under "evaluate". The code is tested in tensorflow 1.14. Let me know if you have questions regarding the code. Sorry for the delay.

Can you provide the detail code of the network? I tried to convert it to pytorch and load the pretrained weight from the checkpoint of tensorflow, but I can get same results. May be there are some difference on data flow, so I need your help.

**Comment by dariofuoli** [comment]
Update:
1. Uploaded original model definition of the paper in tensorflow (data loading and training details to be added).
2. Uploaded a complete implementation in pytorch (note, this version implements a model with RGB output, as opposed to Y as in the paper. For adaptation to Y output, please refer to code in "evaluate/super_resolve.py" for color space transformations).
3. The original model checkpoints of RLSP-64, RLSP-128 are available in the folder "evaluate", along with a script to evaluate your own videos.

Feel free to ask any questions.

**Comment by automatic0313** [comment]
I am very interested in this project. Could you publish datasets？

**Comment by dariofuoli** [comment]
Hi, the details for the datasets are in the paper. We used the dataset from: Frame-Recurrent Video Super-Resolution (https://github.com/msmsajjadi/FRVSR)
